# Generated by Django 2.0.5 on 2018-05-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='createdDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
