# Generated by Django 2.0.5 on 2018-05-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
