# Generated by Django 2.0.2 on 2018-05-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_postmodel_image'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentsModel',
            new_name='Comments',
        ),
    ]
